<a href="https://colab.research.google.com/github/Allesgut7/Praktikum-Matkom/blob/master/Praktikum_Matkom%20Part%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Matrix 9x9 A, B, dan c
import numpy as np
A = np.array ([[1, 2, 3, 4, 5, 6, 7, 8, 9], [2, 3, 4, 5, 6, 7, 8, 9, 0], [3, 4, 5, 6, 7, 8, 9, 0, 1], [4, 5, 6, 7, 8, 9, 0, 1, 2], [5, 6, 7, 8, 9, 0, 1, 2, 3, ], [6, 7, 8, 9, 0, 1, 2, 3, 4], [7, 8, 9, 0, 1, 2, 3, 4, 5], [8, 9, 0, 1, 2, 3, 4, 5, 6], [9, 0, 1, 2, 3, 4, 5, 6, 7]])
B = np.array ([[0, 9, 8, 7, 6, 5, 4, 3, 2], [9, 8, 7, 6, 5, 4, 3, 2, 1], [8, 7, 6, 5, 4, 3, 2, 1, 0], [7, 6, 5, 4, 3, 2, 1, 0, 9], [6, 5, 4, 3, 2, 1, 0, 9, 8], [5, 4, 3, 2, 1, 0, 9, 8, 7], [4, 3, 2, 1, 0, 9, 8, 7, 6], [3, 2, 1, 0, 9, 8, 7, 6, 5], [2, 1, 0, 9, 8, 7, 6, 5, 4]])
C = np.array ([[1, 2, 1, 2, 1, 2, 1, 2, 1], [2, 3, 2, 3, 2, 3, 2, 3, 2], [3, 4, 3, 4, 3, 4, 3, 4, 3], [4, 5, 4, 5, 4, 5, 4, 5, 4], [5, 6, 5, 6, 5, 6, 5, 6, 5], [6, 7, 6, 7, 6, 7, 6, 7, 6,], [7, 8, 7, 8, 7, 8, 7, 8, 7], [8, 9, 8, 9, 8, 9, 8, 9, 8], [9, 0, 9, 0, 9, 0, 9, 0, 9]])
print ("A=", A)
print ("B=", B)
print ("C=", C)

A= [[1 2 3 4 5 6 7 8 9]
 [2 3 4 5 6 7 8 9 0]
 [3 4 5 6 7 8 9 0 1]
 [4 5 6 7 8 9 0 1 2]
 [5 6 7 8 9 0 1 2 3]
 [6 7 8 9 0 1 2 3 4]
 [7 8 9 0 1 2 3 4 5]
 [8 9 0 1 2 3 4 5 6]
 [9 0 1 2 3 4 5 6 7]]
B= [[0 9 8 7 6 5 4 3 2]
 [9 8 7 6 5 4 3 2 1]
 [8 7 6 5 4 3 2 1 0]
 [7 6 5 4 3 2 1 0 9]
 [6 5 4 3 2 1 0 9 8]
 [5 4 3 2 1 0 9 8 7]
 [4 3 2 1 0 9 8 7 6]
 [3 2 1 0 9 8 7 6 5]
 [2 1 0 9 8 7 6 5 4]]
C= [[1 2 1 2 1 2 1 2 1]
 [2 3 2 3 2 3 2 3 2]
 [3 4 3 4 3 4 3 4 3]
 [4 5 4 5 4 5 4 5 4]
 [5 6 5 6 5 6 5 6 5]
 [6 7 6 7 6 7 6 7 6]
 [7 8 7 8 7 8 7 8 7]
 [8 9 8 9 8 9 8 9 8]
 [9 0 9 0 9 0 9 0 9]]


In [ ]:
#Penjumlahan 3 matrix
A = np.array ([[1, 2, 3, 4, 5, 6, 7, 8, 9], [2, 3, 4, 5, 6, 7, 8, 9, 0], [3, 4, 5, 6, 7, 8, 9, 0, 1], [4, 5, 6, 7, 8, 9, 0, 1, 2], [5, 6, 7, 8, 9, 0, 1, 2, 3, ], [6, 7, 8, 9, 0, 1, 2, 3, 4], [7, 8, 9, 0, 1, 2, 3, 4, 5], [8, 9, 0, 1, 2, 3, 4, 5, 6], [9, 0, 1, 2, 3, 4, 5, 6, 7]])
B = np.array ([[0, 9, 8, 7, 6, 5, 4, 3, 2], [9, 8, 7, 6, 5, 4, 3, 2, 1], [8, 7, 6, 5, 4, 3, 2, 1, 0], [7, 6, 5, 4, 3, 2, 1, 0, 9], [6, 5, 4, 3, 2, 1, 0, 9, 8], [5, 4, 3, 2, 1, 0, 9, 8, 7], [4, 3, 2, 1, 0, 9, 8, 7, 6], [3, 2, 1, 0, 9, 8, 7, 6, 5], [2, 1, 0, 9, 8, 7, 6, 5, 4]])
C = np.array ([[1, 2, 1, 2, 1, 2, 1, 2, 1], [2, 3, 2, 3, 2, 3, 2, 3, 2], [3, 4, 3, 4, 3, 4, 3, 4, 3], [4, 5, 4, 5, 4, 5, 4, 5, 4], [5, 6, 5, 6, 5, 6, 5, 6, 5], [6, 7, 6, 7, 6, 7, 6, 7, 6,], [7, 8, 7, 8, 7, 8, 7, 8, 7], [8, 9, 8, 9, 8, 9, 8, 9, 8], [9, 0, 9, 0, 9, 0, 9, 0, 9]])
A+B+C

array([[ 2, 13, 12, 13, 12, 13, 12, 13, 12],
       [13, 14, 13, 14, 13, 14, 13, 14,  3],
       [14, 15, 14, 15, 14, 15, 14,  5,  4],
       [15, 16, 15, 16, 15, 16,  5,  6, 15],
       [16, 17, 16, 17, 16,  7,  6, 17, 16],
       [17, 18, 17, 18,  7,  8, 17, 18, 17],
       [18, 19, 18,  9,  8, 19, 18, 19, 18],
       [19, 20,  9, 10, 19, 20, 19, 20, 19],
       [20,  1, 10, 11, 20, 11, 20, 11, 20]])

In [ ]:
#Pengurangan 3 matrix
A = np.array ([[1, 2, 3, 4, 5, 6, 7, 8, 9], [2, 3, 4, 5, 6, 7, 8, 9, 0], [3, 4, 5, 6, 7, 8, 9, 0, 1], [4, 5, 6, 7, 8, 9, 0, 1, 2], [5, 6, 7, 8, 9, 0, 1, 2, 3, ], [6, 7, 8, 9, 0, 1, 2, 3, 4], [7, 8, 9, 0, 1, 2, 3, 4, 5], [8, 9, 0, 1, 2, 3, 4, 5, 6], [9, 0, 1, 2, 3, 4, 5, 6, 7]])
B = np.array ([[0, 9, 8, 7, 6, 5, 4, 3, 2], [9, 8, 7, 6, 5, 4, 3, 2, 1], [8, 7, 6, 5, 4, 3, 2, 1, 0], [7, 6, 5, 4, 3, 2, 1, 0, 9], [6, 5, 4, 3, 2, 1, 0, 9, 8], [5, 4, 3, 2, 1, 0, 9, 8, 7], [4, 3, 2, 1, 0, 9, 8, 7, 6], [3, 2, 1, 0, 9, 8, 7, 6, 5], [2, 1, 0, 9, 8, 7, 6, 5, 4]])
C = np.array ([[1, 2, 1, 2, 1, 2, 1, 2, 1], [2, 3, 2, 3, 2, 3, 2, 3, 2], [3, 4, 3, 4, 3, 4, 3, 4, 3], [4, 5, 4, 5, 4, 5, 4, 5, 4], [5, 6, 5, 6, 5, 6, 5, 6, 5], [6, 7, 6, 7, 6, 7, 6, 7, 6,], [7, 8, 7, 8, 7, 8, 7, 8, 7], [8, 9, 8, 9, 8, 9, 8, 9, 8], [9, 0, 9, 0, 9, 0, 9, 0, 9]])
B-C-A

array([[ -2,   5,   4,   1,   0,  -3,  -4,  -7,  -8],
       [  5,   2,   1,  -2,  -3,  -6,  -7, -10,  -1],
       [  2,  -1,  -2,  -5,  -6,  -9, -10,  -3,  -4],
       [ -1,  -4,  -5,  -8,  -9, -12,  -3,  -6,   3],
       [ -4,  -7,  -8, -11, -12,  -5,  -6,   1,   0],
       [ -7, -10, -11, -14,  -5,  -8,   1,  -2,  -3],
       [-10, -13, -14,  -7,  -8,  -1,  -2,  -5,  -6],
       [-13, -16,  -7, -10,  -1,  -4,  -5,  -8,  -9],
       [-16,   1, -10,   7,  -4,   3,  -8,  -1, -12]])

In [ ]:
#Matrix Transpose
A = np.array ([[1, 2, 3, 4, 5, 6, 7, 8, 9], [2, 3, 4, 5, 6, 7, 8, 9, 0], [3, 4, 5, 6, 7, 8, 9, 0, 1], [4, 5, 6, 7, 8, 9, 0, 1, 2], [5, 6, 7, 8, 9, 0, 1, 2, 3, ], [6, 7, 8, 9, 0, 1, 2, 3, 4], [7, 8, 9, 0, 1, 2, 3, 4, 5], [8, 9, 0, 1, 2, 3, 4, 5, 6], [9, 0, 1, 2, 3, 4, 5, 6, 7]])
A.T

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9, 0],
       [3, 4, 5, 6, 7, 8, 9, 0, 1],
       [4, 5, 6, 7, 8, 9, 0, 1, 2],
       [5, 6, 7, 8, 9, 0, 1, 2, 3],
       [6, 7, 8, 9, 0, 1, 2, 3, 4],
       [7, 8, 9, 0, 1, 2, 3, 4, 5],
       [8, 9, 0, 1, 2, 3, 4, 5, 6],
       [9, 0, 1, 2, 3, 4, 5, 6, 7]])

In [ ]:
#Invers Matrix C 
import numpy as np

C = np.array ([[1, 2, 1, 2, 1, 2, 1, 2, 1],
               [2, 3, 2, 3, 2, 3, 2, 3, 2],
               [3, 4, 3, 4, 3, 4, 3, 4, 3],
               [4, 5, 4, 5, 4, 5, 4, 5, 4],
               [5, 6, 5, 6, 5, 6, 5, 6, 5],
               [6, 7, 6, 7, 6, 7, 6, 7, 6,],
               [7, 8, 7, 8, 7, 8, 7, 8, 7],
               [8, 9, 8, 9, 8, 9, 8, 9, 8],
               [9, 0, 9, 0, 9, 0, 9, 0, 9]])

print(np.linalg.pinv(C))

[[-0.00167952 -0.00130249 -0.00092545 -0.00054841 -0.00017138  0.00020566
   0.00058269  0.00095973  0.02190231]
 [ 0.0035347   0.00401671  0.00449871  0.00498072  0.00546272  0.00594473
   0.00642674  0.00690874 -0.02313625]
 [-0.00167952 -0.00130249 -0.00092545 -0.00054841 -0.00017138  0.00020566
   0.00058269  0.00095973  0.02190231]
 [ 0.0035347   0.00401671  0.00449871  0.00498072  0.00546272  0.00594473
   0.00642674  0.00690874 -0.02313625]
 [-0.00167952 -0.00130249 -0.00092545 -0.00054841 -0.00017138  0.00020566
   0.00058269  0.00095973  0.02190231]
 [ 0.0035347   0.00401671  0.00449871  0.00498072  0.00546272  0.00594473
   0.00642674  0.00690874 -0.02313625]
 [-0.00167952 -0.00130249 -0.00092545 -0.00054841 -0.00017138  0.00020566
   0.00058269  0.00095973  0.02190231]
 [ 0.0035347   0.00401671  0.00449871  0.00498072  0.00546272  0.00594473
   0.00642674  0.00690874 -0.02313625]
 [-0.00167952 -0.00130249 -0.00092545 -0.00054841 -0.00017138  0.00020566
   0.00058269  0.00095

In [ ]:
#Determinan A, B, dan C
import numpy as np

A = np.array ([[1, 2, 3, 4, 5, 6, 7, 8, 9], [2, 3, 4, 5, 6, 7, 8, 9, 0], [3, 4, 5, 6, 7, 8, 9, 0, 1], [4, 5, 6, 7, 8, 9, 0, 1, 2], [5, 6, 7, 8, 9, 0, 1, 2, 3, ], [6, 7, 8, 9, 0, 1, 2, 3, 4], [7, 8, 9, 0, 1, 2, 3, 4, 5], [8, 9, 0, 1, 2, 3, 4, 5, 6], [9, 0, 1, 2, 3, 4, 5, 6, 7]])
B = np.array ([[0, 9, 8, 7, 6, 5, 4, 3, 2], [9, 8, 7, 6, 5, 4, 3, 2, 1], [8, 7, 6, 5, 4, 3, 2, 1, 0], [7, 6, 5, 4, 3, 2, 1, 0, 9], [6, 5, 4, 3, 2, 1, 0, 9, 8], [5, 4, 3, 2, 1, 0, 9, 8, 7], [4, 3, 2, 1, 0, 9, 8, 7, 6], [3, 2, 1, 0, 9, 8, 7, 6, 5], [2, 1, 0, 9, 8, 7, 6, 5, 4]])
C = np.array ([[1, 2, 1, 2, 1, 2, 1, 2, 1], [2, 3, 2, 3, 2, 3, 2, 3, 2], [3, 4, 3, 4, 3, 4, 3, 4, 3], [4, 5, 4, 5, 4, 5, 4, 5, 4], [5, 6, 5, 6, 5, 6, 5, 6, 5], [6, 7, 6, 7, 6, 7, 6, 7, 6,], [7, 8, 7, 8, 7, 8, 7, 8, 7], [8, 9, 8, 9, 8, 9, 8, 9, 8], [9, 0, 9, 0, 9, 0, 9, 0, 9]])

det = print("A=",(np.linalg.det(A)))
det = print("B=",(np.linalg.det(B)))
det = print("C=",(np.linalg.det(C)))

A= 460000000.00000113
B= -9999999.99999997
C= 0.0


In [ ]:
#Perkalian A*B
A = np.array ([[1, 2, 3, 4, 5, 6, 7, 8, 9], [2, 3, 4, 5, 6, 7, 8, 9, 0], [3, 4, 5, 6, 7, 8, 9, 0, 1], [4, 5, 6, 7, 8, 9, 0, 1, 2], [5, 6, 7, 8, 9, 0, 1, 2, 3, ], [6, 7, 8, 9, 0, 1, 2, 3, 4], [7, 8, 9, 0, 1, 2, 3, 4, 5], [8, 9, 0, 1, 2, 3, 4, 5, 6], [9, 0, 1, 2, 3, 4, 5, 6, 7]])
B = np.array ([[0, 9, 8, 7, 6, 5, 4, 3, 2], [9, 8, 7, 6, 5, 4, 3, 2, 1], [8, 7, 6, 5, 4, 3, 2, 1, 0], [7, 6, 5, 4, 3, 2, 1, 0, 9], [6, 5, 4, 3, 2, 1, 0, 9, 8], [5, 4, 3, 2, 1, 0, 9, 8, 7], [4, 3, 2, 1, 0, 9, 8, 7, 6], [3, 2, 1, 0, 9, 8, 7, 6, 5], [2, 1, 0, 9, 8, 7, 6, 5, 4]])
A*B

array([[ 0, 18, 24, 28, 30, 30, 28, 24, 18],
       [18, 24, 28, 30, 30, 28, 24, 18,  0],
       [24, 28, 30, 30, 28, 24, 18,  0,  0],
       [28, 30, 30, 28, 24, 18,  0,  0, 18],
       [30, 30, 28, 24, 18,  0,  0, 18, 24],
       [30, 28, 24, 18,  0,  0, 18, 24, 28],
       [28, 24, 18,  0,  0, 18, 24, 28, 30],
       [24, 18,  0,  0, 18, 24, 28, 30, 30],
       [18,  0,  0, 18, 24, 28, 30, 30, 28]])

In [ ]:
#Perkalian A*B*C
A = np.array ([[1, 2, 3, 4, 5, 6, 7, 8, 9], [2, 3, 4, 5, 6, 7, 8, 9, 0], [3, 4, 5, 6, 7, 8, 9, 0, 1], [4, 5, 6, 7, 8, 9, 0, 1, 2], [5, 6, 7, 8, 9, 0, 1, 2, 3, ], [6, 7, 8, 9, 0, 1, 2, 3, 4], [7, 8, 9, 0, 1, 2, 3, 4, 5], [8, 9, 0, 1, 2, 3, 4, 5, 6], [9, 0, 1, 2, 3, 4, 5, 6, 7]])
B = np.array ([[0, 9, 8, 7, 6, 5, 4, 3, 2], [9, 8, 7, 6, 5, 4, 3, 2, 1], [8, 7, 6, 5, 4, 3, 2, 1, 0], [7, 6, 5, 4, 3, 2, 1, 0, 9], [6, 5, 4, 3, 2, 1, 0, 9, 8], [5, 4, 3, 2, 1, 0, 9, 8, 7], [4, 3, 2, 1, 0, 9, 8, 7, 6], [3, 2, 1, 0, 9, 8, 7, 6, 5], [2, 1, 0, 9, 8, 7, 6, 5, 4]])
C = np.array ([[1, 2, 1, 2, 1, 2, 1, 2, 1], [2, 3, 2, 3, 2, 3, 2, 3, 2], [3, 4, 3, 4, 3, 4, 3, 4, 3], [4, 5, 4, 5, 4, 5, 4, 5, 4], [5, 6, 5, 6, 5, 6, 5, 6, 5], [6, 7, 6, 7, 6, 7, 6, 7, 6,], [7, 8, 7, 8, 7, 8, 7, 8, 7], [8, 9, 8, 9, 8, 9, 8, 9, 8], [9, 0, 9, 0, 9, 0, 9, 0, 9]])
A*B*C

array([[  0,  36,  24,  56,  30,  60,  28,  48,  18],
       [ 36,  72,  56,  90,  60,  84,  48,  54,   0],
       [ 72, 112,  90, 120,  84,  96,  54,   0,   0],
       [112, 150, 120, 140,  96,  90,   0,   0,  72],
       [150, 180, 140, 144,  90,   0,   0, 108, 120],
       [180, 196, 144, 126,   0,   0, 108, 168, 168],
       [196, 192, 126,   0,   0, 144, 168, 224, 210],
       [192, 162,   0,   0, 144, 216, 224, 270, 240],
       [162,   0,   0,   0, 216,   0, 270,   0, 252]])